# Generated by Django 5.1.5 on 2025-02-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='Id',
            field=models.IntegerField(default=1),
        ),
    ]
