# Generated by Django 5.1.5 on 2025-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='Id',
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
